// ─── KPI Data ─────────────────────────────────────────────────────────────────
export const KPI_DATA = [
  {
    id: 'revenue',
    label: 'Total Revenue',
    value: '$284,500',
    rawValue: 284500,
    trend: 18.2,
    period: 'vs last month',
    icon: 'DollarSign',
    color: 'teal',
    bgColor: 'bg-teal-50',
    iconColor: 'text-teal-600',
    borderColor: 'border-teal-200',
  },
  {
    id: 'leads',
    label: 'Active Leads',
    value: '1,284',
    rawValue: 1284,
    trend: 12.5,
    period: 'vs last month',
    icon: 'Target',
    color: 'blue',
    bgColor: 'bg-blue-50',
    iconColor: 'text-blue-600',
    borderColor: 'border-blue-200',
  },
  {
    id: 'conversion',
    label: 'Conversion Rate',
    value: '24.8%',
    rawValue: 24.8,
    trend: 3.1,
    period: 'vs last month',
    icon: 'TrendingUp',
    color: 'emerald',
    bgColor: 'bg-emerald-50',
    iconColor: 'text-emerald-600',
    borderColor: 'border-emerald-200',
  },
  {
    id: 'deals',
    label: 'Deals Closed',
    value: '48',
    rawValue: 48,
    trend: -4.2,
    period: 'vs last month',
    icon: 'HeartHandshake',
    color: 'amber',
    bgColor: 'bg-amber-50',
    iconColor: 'text-amber-600',
    borderColor: 'border-amber-200',
  },
]

// ─── Revenue Chart Data ────────────────────────────────────────────────────────
export const REVENUE_DATA = [
  { month: 'Jan', revenue: 42000, target: 40000, deals: 18 },
  { month: 'Feb', revenue: 38500, target: 42000, deals: 16 },
  { month: 'Mar', revenue: 51200, target: 44000, deals: 22 },
  { month: 'Apr', revenue: 46800, target: 46000, deals: 20 },
  { month: 'May', revenue: 58400, target: 48000, deals: 26 },
  { month: 'Jun', revenue: 54200, target: 50000, deals: 24 },
  { month: 'Jul', revenue: 63100, target: 52000, deals: 28 },
  { month: 'Aug', revenue: 71500, target: 55000, deals: 32 },
  { month: 'Sep', revenue: 68900, target: 58000, deals: 30 },
  { month: 'Oct', revenue: 79200, target: 62000, deals: 36 },
  { month: 'Nov', revenue: 84500, target: 66000, deals: 38 },
  { month: 'Dec', revenue: 91800, target: 70000, deals: 42 },
]

// ─── Pipeline Funnel Data ──────────────────────────────────────────────────────
export const PIPELINE_DATA = [
  { stage: 'New',          count: 384, value: 1920000, color: '#3b82f6', pct: 100 },
  { stage: 'Contacted',   count: 271, value: 1355000, color: '#8b5cf6', pct: 71  },
  { stage: 'Qualified',   count: 189, value:  945000, color: '#14b8a6', pct: 49  },
  { stage: 'Proposal',    count: 124, value:  620000, color: '#f59e0b', pct: 32  },
  { stage: 'Negotiation', count:  87, value:  435000, color: '#f97316', pct: 23  },
  { stage: 'Won',         count:  48, value:  240000, color: '#10b981', pct: 13  },
]

// ─── Activity Feed ─────────────────────────────────────────────────────────────
export const ACTIVITY_DATA = [
  {
    id: 1,
    type: 'deal_won',
    user: 'Alex Rivera',
    action: 'closed a deal with',
    subject: 'TechCorp Inc.',
    detail: '$24,000 · Enterprise Plan',
    time: '2 minutes ago',
    avatar: null,
  },
  {
    id: 2,
    type: 'lead_qualified',
    user: 'Morgan Chen',
    action: 'qualified lead',
    subject: 'Meridian Solutions',
    detail: 'Moved to Qualified stage',
    time: '18 minutes ago',
    avatar: null,
  },
  {
    id: 3,
    type: 'meeting_scheduled',
    user: 'Jordan Kim',
    action: 'scheduled a demo with',
    subject: 'Acme Corp',
    detail: 'Tomorrow at 2:00 PM',
    time: '1 hour ago',
    avatar: null,
  },
  {
    id: 4,
    type: 'note_added',
    user: 'Taylor Brooks',
    action: 'added a note to',
    subject: 'GlobalX',
    detail: 'Decision expected end of week',
    time: '2 hours ago',
    avatar: null,
  },
  {
    id: 5,
    type: 'lead_created',
    user: 'Alex Rivera',
    action: 'created new lead',
    subject: 'Nexaflow Technologies',
    detail: 'Inbound · SaaS · $45K potential',
    time: '3 hours ago',
    avatar: null,
  },
  {
    id: 6,
    type: 'deal_lost',
    user: 'Morgan Chen',
    action: 'marked as lost',
    subject: 'Vertex Systems',
    detail: 'Lost to competitor',
    time: '5 hours ago',
    avatar: null,
  },
  {
    id: 7,
    type: 'follow_up',
    user: 'Jordan Kim',
    action: 'completed follow-up with',
    subject: 'Bright Digital',
    detail: 'Contract sent for review',
    time: '6 hours ago',
    avatar: null,
  },
]

// ─── Top Performers ────────────────────────────────────────────────────────────
export const PERFORMERS_DATA = [
  { id: 1, name: 'Alex Rivera',   role: 'Admin',     deals: 14, revenue: 84200, quota: 92, avatar: null },
  { id: 2, name: 'Morgan Chen',   role: 'Manager',   deals: 11, revenue: 67400, quota: 87, avatar: null },
  { id: 3, name: 'Jordan Kim',    role: 'AGM',       deals: 9,  revenue: 54800, quota: 78, avatar: null },
  { id: 4, name: 'Taylor Brooks', role: 'Executive', deals: 8,  revenue: 48100, quota: 72, avatar: null },
  { id: 5, name: 'Sam Nguyen',    role: 'Executive', deals: 6,  revenue: 30000, quota: 61, avatar: null },
]

// ─── Monthly Leads Chart Data ──────────────────────────────────────────────────
export const LEADS_MONTHLY = [
  { month: 'Jan', new: 62, won: 18, lost: 12 },
  { month: 'Feb', new: 58, won: 16, lost: 14 },
  { month: 'Mar', new: 74, won: 22, lost: 10 },
  { month: 'Apr', new: 68, won: 20, lost: 16 },
  { month: 'May', new: 82, won: 26, lost: 12 },
  { month: 'Jun', new: 76, won: 24, lost: 15 },
  { month: 'Jul', new: 91, won: 28, lost: 11 },
  { month: 'Aug', new: 96, won: 32, lost: 14 },
  { month: 'Sep', new: 88, won: 30, lost: 13 },
  { month: 'Oct', new: 104, won: 36, lost: 16 },
  { month: 'Nov', new: 112, won: 38, lost: 18 },
  { month: 'Dec', new: 124, won: 42, lost: 20 },
]
