-- ─── Accord CRM — Contacts Table Migration ────────────────────────────────────
--
-- Run this in Supabase Dashboard → SQL Editor.
-- Safe to re-run: uses IF NOT EXISTS / DROP IF EXISTS throughout.
--
-- Column names match contactsService.js toApp() / toDb() mappers (snake_case).

-- ── Enable extensions ─────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── Contacts table ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.contacts (
  -- UUID generated by Postgres — the app never provides an id on insert
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Core identity
  name            TEXT        NOT NULL,
  company         TEXT        NOT NULL DEFAULT '',
  designation     TEXT                 DEFAULT '',
  email           TEXT                 DEFAULT '',
  phone           TEXT                 DEFAULT '',

  -- Categorical (must match CONTACT_TYPES / CONTACT_STATUSES in contactsData.js)
  type            TEXT        NOT NULL DEFAULT 'Prospect',
  status          TEXT        NOT NULL DEFAULT 'Active',

  -- Assignment
  assignee        TEXT                 DEFAULT '',
  linked_lead_id  TEXT,          -- soft link to leads.id, no FK

  -- Extended details
  address         TEXT                 DEFAULT '',
  website         TEXT                 DEFAULT '',
  notes           TEXT                 DEFAULT '',
  tags            TEXT[]               DEFAULT '{}',
  avatar          TEXT,

  -- Dates stored as DATE to match the app's YYYY-MM-DD strings
  created_at      DATE        NOT NULL DEFAULT CURRENT_DATE,
  last_activity   DATE        NOT NULL DEFAULT CURRENT_DATE
);

-- ── Row Level Security ────────────────────────────────────────────────────────
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can access contacts" ON public.contacts;

CREATE POLICY "Authenticated users can access contacts"
  ON public.contacts
  FOR ALL
  USING  (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS contacts_last_activity_idx ON public.contacts (last_activity DESC);
CREATE INDEX IF NOT EXISTS contacts_email_idx         ON public.contacts (lower(email));
CREATE INDEX IF NOT EXISTS contacts_name_idx          ON public.contacts (lower(name));
CREATE INDEX IF NOT EXISTS contacts_company_idx       ON public.contacts (lower(company));

-- ── Confirm ───────────────────────────────────────────────────────────────────
-- SELECT column_name, data_type, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'contacts' ORDER BY ordinal_position;
