-- ─── Accord CRM — Leads Table Migration ──────────────────────────────────────
--
-- Run in: Supabase Dashboard → SQL Editor
-- Safe to re-run: uses IF NOT EXISTS / DROP IF EXISTS throughout.
--
-- Column names match leadsService.js toApp() / toDb() mappers (snake_case).
-- App camelCase fields are translated in the service layer.

-- ── Enable extensions ─────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── Leads table ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.leads (
  -- UUID generated by Postgres — the app never provides an id on insert
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Core identity
  name            TEXT        NOT NULL,
  company         TEXT                    DEFAULT '',
  email           TEXT                    DEFAULT '',
  phone           TEXT                    DEFAULT '',

  -- Pipeline
  -- stage: must match STAGES in leadsStore.js
  -- ('New' | 'Contacted' | 'Qualified' | 'Proposal' | 'Negotiation' | 'Won' | 'Lost')
  stage           TEXT        NOT NULL    DEFAULT 'New',

  -- Deal
  -- value: stored as NUMERIC, returned as number in JS via toApp()
  value           NUMERIC                 DEFAULT 0,

  -- Source: must match SOURCES in leadsStore.js
  source          TEXT                    DEFAULT '',

  -- Assignment: must match ASSIGNEES in leadsStore.js
  assignee        TEXT                    DEFAULT '',

  -- Priority: must match PRIORITIES in leadsStore.js
  -- ('High' | 'Medium' | 'Low')
  priority        TEXT        NOT NULL    DEFAULT 'Medium',

  -- Notes and tags
  notes           TEXT                    DEFAULT '',
  tags            TEXT[]                  DEFAULT '{}',

  -- Timestamps (DATE to match the app's YYYY-MM-DD strings)
  -- last_activity → app's lastActivity (used for default sort)
  -- created_at    → app's createdAt
  created_at      DATE        NOT NULL    DEFAULT CURRENT_DATE,
  last_activity   DATE        NOT NULL    DEFAULT CURRENT_DATE
);

-- ── Row Level Security ────────────────────────────────────────────────────────
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can access leads" ON public.leads;

CREATE POLICY "Authenticated users can access leads"
  ON public.leads
  FOR ALL
  USING     (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ── Indexes ───────────────────────────────────────────────────────────────────
-- Default sort is last_activity DESC; stage and value are common filter/sort columns
CREATE INDEX IF NOT EXISTS leads_last_activity_idx ON public.leads (last_activity DESC);
CREATE INDEX IF NOT EXISTS leads_stage_idx         ON public.leads (stage);
CREATE INDEX IF NOT EXISTS leads_priority_idx      ON public.leads (priority);
CREATE INDEX IF NOT EXISTS leads_assignee_idx      ON public.leads (lower(assignee));
CREATE INDEX IF NOT EXISTS leads_value_idx         ON public.leads (value DESC);
CREATE INDEX IF NOT EXISTS leads_created_at_idx    ON public.leads (created_at DESC);

-- ── Verify ────────────────────────────────────────────────────────────────────
-- SELECT column_name, data_type, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'leads'
-- ORDER BY ordinal_position;
