-- ─── Accord CRM — Meetings Table Migration ────────────────────────────────────
--
-- Run in: Supabase Dashboard → SQL Editor
-- Safe to re-run: uses IF NOT EXISTS / DROP IF EXISTS throughout.
--
-- Column names match meetingsService.js toApp() / toDb() mappers (snake_case).
-- The app's camelCase fields are translated in the service layer.

-- ── Enable extensions ─────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── Meetings table ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.meetings (
  -- UUID generated by Postgres — the app never provides an id on insert
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Core fields
  title           TEXT        NOT NULL,
  description     TEXT                    DEFAULT '',

  -- Status: must match MEETING_STATUSES in meetingsData.js
  -- ('Scheduled' | 'Completed' | 'Cancelled' | 'Rescheduled')
  status          TEXT        NOT NULL    DEFAULT 'Scheduled',

  -- Type: must match MEETING_TYPES in meetingsData.js
  type            TEXT        NOT NULL    DEFAULT 'Discovery',

  -- Scheduling
  -- scheduled_date: DATE  (maps to app's scheduledDate, e.g. '2026-05-13')
  -- scheduled_time: TIME  (maps to app's scheduledTime, e.g. '10:00')
  scheduled_date  DATE,
  scheduled_time  TIME,
  duration_mins   INTEGER                 DEFAULT 60,

  -- Location
  location        TEXT                    DEFAULT '',
  location_url    TEXT                    DEFAULT '',

  -- People
  organizer       TEXT                    DEFAULT '',
  -- participants: TEXT[] — array of name strings (e.g. ['Alice', 'Bob'])
  participants    TEXT[]                  DEFAULT '{}',

  -- Related entity (Lead or Contact) — soft link, no FK
  related_type    TEXT                    DEFAULT 'None',
  related_id      TEXT                    DEFAULT '',
  related_label   TEXT                    DEFAULT '',

  -- Content
  notes           TEXT                    DEFAULT '',
  tags            TEXT[]                  DEFAULT '{}',

  -- Timestamp (DATE to match app's YYYY-MM-DD strings)
  created_at      DATE        NOT NULL    DEFAULT CURRENT_DATE
);

-- ── Row Level Security ────────────────────────────────────────────────────────
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;

-- Drop old policy so the script is idempotent
DROP POLICY IF EXISTS "Authenticated users can access meetings" ON public.meetings;

-- Any authenticated Supabase user can read and write all meetings.
CREATE POLICY "Authenticated users can access meetings"
  ON public.meetings
  FOR ALL
  USING     (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ── Indexes ───────────────────────────────────────────────────────────────────
-- Default sort is scheduled_date ASC; also index by status and organizer
CREATE INDEX IF NOT EXISTS meetings_scheduled_date_idx ON public.meetings (scheduled_date ASC NULLS LAST);
CREATE INDEX IF NOT EXISTS meetings_status_idx         ON public.meetings (status);
CREATE INDEX IF NOT EXISTS meetings_type_idx           ON public.meetings (type);
CREATE INDEX IF NOT EXISTS meetings_organizer_idx      ON public.meetings (lower(organizer));
CREATE INDEX IF NOT EXISTS meetings_created_at_idx     ON public.meetings (created_at DESC);

-- ── Verify ────────────────────────────────────────────────────────────────────
-- After running, confirm with:
-- SELECT column_name, data_type, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'meetings'
-- ORDER BY ordinal_position;
