-- ─── Accord CRM — Tasks Table Migration ──────────────────────────────────────
--
-- Run this in: Supabase Dashboard → SQL Editor
-- Safe to re-run: uses IF NOT EXISTS / DROP IF EXISTS / CREATE OR REPLACE.
--
-- Column names match tasksService.js toApp() / toDb() mappers (snake_case).
-- The app's camelCase fields are mapped in the service layer.

-- ── Enable extensions ─────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── Tasks table ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tasks (
  -- UUID generated by Postgres — the app never provides an id on insert
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Core fields
  title           TEXT        NOT NULL,
  description     TEXT                    DEFAULT '',

  -- Status: must match TASK_STATUSES in tasksData.js
  -- ('Todo' | 'In Progress' | 'Completed' | 'Overdue')
  status          TEXT        NOT NULL    DEFAULT 'Todo',

  -- Priority: must match TASK_PRIORITIES in tasksData.js
  -- ('Low' | 'Medium' | 'High' | 'Urgent')
  priority        TEXT        NOT NULL    DEFAULT 'Medium',

  -- Scheduling
  due_date        DATE,                   -- null means no due date set
  assignee        TEXT                    DEFAULT '',

  -- Related entity (Lead or Contact)
  related_type    TEXT                    DEFAULT 'None',
  related_id      TEXT                    DEFAULT '',
  related_label   TEXT                    DEFAULT '',

  -- Completion tracking
  -- Set automatically by the service when status → 'Completed'
  -- Cleared automatically when status moves away from 'Completed'
  completed_at    DATE,

  -- Tags stored as a Postgres TEXT array; supabase-js sends/receives as JS string[]
  tags            TEXT[]                  DEFAULT '{}',

  -- Timestamps (DATE to match the app's YYYY-MM-DD strings)
  created_at      DATE        NOT NULL    DEFAULT CURRENT_DATE
);

-- ── Row Level Security ────────────────────────────────────────────────────────
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Drop any old policy so this script is idempotent
DROP POLICY IF EXISTS "Authenticated users can access tasks" ON public.tasks;

-- Any signed-in Supabase user can read and write all tasks.
-- Tighten later (e.g. per-user or per-team scoping) without touching app code.
CREATE POLICY "Authenticated users can access tasks"
  ON public.tasks
  FOR ALL
  USING     (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- ── Indexes ───────────────────────────────────────────────────────────────────
-- Default sort + common filter columns
CREATE INDEX IF NOT EXISTS tasks_due_date_idx    ON public.tasks (due_date ASC NULLS LAST);
CREATE INDEX IF NOT EXISTS tasks_status_idx      ON public.tasks (status);
CREATE INDEX IF NOT EXISTS tasks_priority_idx    ON public.tasks (priority);
CREATE INDEX IF NOT EXISTS tasks_assignee_idx    ON public.tasks (lower(assignee));
CREATE INDEX IF NOT EXISTS tasks_created_at_idx  ON public.tasks (created_at DESC);

-- ── Verify ────────────────────────────────────────────────────────────────────
-- After running, confirm with:
-- SELECT column_name, data_type, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'tasks'
-- ORDER BY ordinal_position;
